trigger:
- main

pool:
  name: default  # Vérifie que ce pool contient un agent compatible avec Java, Docker et SonarCloud

steps:

# 1️⃣ Checkout du code
- checkout: self
  clean: true
  persistCredentials: true