apiVersion: apps/v1
kind: Deployment
metadata:
  name: projetdevops-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projetdevops
  template:
    metadata:
      labels:
        app: projetdevops
    spec:
      containers:
      - name: projetdevops-container
        image: hanen90/devops-azure:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: projetdevops-service
spec:
  type: LoadBalancer
  selector:
    app: projetdevops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80